/*
 * SPDX-FileCopyrightText: Copyright 2025-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.arm.voiceassistant.utils

import android.net.Uri

/**
 * Timing and performance statistics associated with a chat interaction.
 *
 * @param sttTime Speech-to-text latency in seconds
 * @param llmEncodeTps LLM encode throughput (tokens per second)
 * @param llmDecodeTps LLM decode throughput (tokens per second)
 */
data class TimingStats(
    val sttTime: String,
    val llmEncodeTps: String,
    val llmDecodeTps: String
)

/**
 * Base type for all chat messages exchanged in the conversation.
 */
sealed class ChatMessage {
    /**
     * Text message sent by the user.
     *
     * @param text User-provided text
     * @param timing Optional timing statistics for the message
     */
    data class UserText(
        val text: String,
        val timing: TimingStats? = null
    ) : ChatMessage()

    /**
     * Image message sent by the user.
     *
     * @param uri URI pointing to the image resource
     */
    data class UserImage(val uri: Uri) : ChatMessage()

    /**
     * Text message generated by the assistant.
     *
     * @param text Assistant-generated response text
     * @param timing Optional timing statistics for the response
     */
    data class AssistantText(
        val text: String,
        val timing: TimingStats? = null
    ) : ChatMessage()
}
